# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-cicd-test-2 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: custom-cicd-test-2
  template:
    metadata:
      labels:
        app: custom-cicd-test-2
    spec:
      containers:
      - name: custom-cicd-test-2
       
        image: ghcr.io/aeskerminen/custom-cicd-test-2:d2ab375735f2c4659309c962a1500b1df6b987aa
        ports:
        - containerPort: 8080