# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-cicd-test-2 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: custom-cicd-test-2
  template:
    metadata:
      labels:
        app: custom-cicd-test-2
    spec:
      containers:
      - name: custom-cicd-test-2
       
        image: ghcr.io/aeskerminen/custom-cicd-test-2:113befefb9f5392e487d31b0aee8627839c00168
        ports:
        - containerPort: 8080