# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: custom-cicd-test-2-service
spec:
  selector:
    app: custom-cicd-test-2
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 30069
  type: NodePort